### ISSUE TITLE
XLS-6d Standard for Visual Account Icons

### ISSUE THREAD

**Issue by RichardAH** [xrp-community/standards-drafts#7]
Following from XLS-5d ( https://github.com/xrp-community/standards-drafts/issues/6 ) it has become necessary to provide XRPL users a way to identify their XRPL account, which effectively now has two different identifiers: an 'r-address' and an 'X-address'.

To solve this problem XLS-6d provides for a standard way to visually identify accounts irrespective of which addressing system is used by the rest of the user interface.

For a user account take the X-address of the account without destination tag and feed it into hashicon https://www.npmjs.com/package/hashicon

For an exchange, take the X-address of the account with the destination tag and feed it into hashicon.

It's recommended that these icons are displayed alongside addresses to help reduce user confusion. See examples in Figures 1 and 2.

![image](https://user-images.githubusercontent.com/19866478/65387069-ba273a80-dd86-11e9-8680-34488e15401d.png)
Figure 1

![image](https://user-images.githubusercontent.com/19866478/65387078-dc20bd00-dd86-11e9-90af-126edf511060.png)
Figure 2

**Comment by codetsunami** [comment]
Example: 
r-addr: r3kmLJN5D28dHuH8vZNUZpMC43pEHpaocV
x-addr: X7tFPvjMH7nDxP8nTGkeeggcUpCZj8nYJkTRDHUikbvmVMB
hashicon: 
![image](https://user-images.githubusercontent.com/19866478/65388972-3c6a2b80-dd94-11e9-9ef3-d8e64ca16d63.png)

r-addr: rGWrZyQqhTp9Xu7G5Pkayo7bXjH4k4QYpf
x-addr: XVLhHMPHU98es4dbozjVtdWzVrDjtV5fdx1mHp98tDMoQXb
hashicon:
![image](https://user-images.githubusercontent.com/19866478/65388989-691e4300-dd94-11e9-8229-0a81b163b776.png)

**Comment by movitto** [comment]
@codetsunami I'm all for visual representations of data but is the hashicon algorithm / standard documented anywhere outside the provided repo? I ask because unless it can be implemented in other languages, this would be limited to javascript based solutions.

Also googling around a bit there are a few other solutions in the same domain, such as [identicons](https://en.wikipedia.org/wiki/Identicon), just curious as to if you've evaluated the tradeoffs?

**Comment by codetsunami** [comment]
@movitto I had a look at the various other identicons on offer. None seem as visually appealing and easy to recognise as these hashicons.

I take your point about support for other languages. I’m happy to port the algorithm that generates them to a couple of other languages if you let me know what you need.

**Comment by movitto** [comment]
> @movitto I had a look at the various other identicons on offer. None seem as visually appealing and easy to recognise as these hashicons.

"None seem as visually appealing" isn't really an objective argument, to support that I'd reference color and pattern variations, algorithm differences, etc. 

> I take your point about support for other languages. I’m happy to port the algorithm that generates them to a couple of other languages if you let me know what you need.

Alot of our stack is in ruby, so would be awesome to have bindings for that. That being said, C bindings probably would be the most portable though, as once those exist, wrappers could be written in any language.

**Comment by codetsunami** [comment]
@movitto if you want to propose a different identicon as being superior please go ahead. At the end of the day everyone will have a different opinion on any graphical representation, there’s no way to come up with an “objectively best” visual.

**Comment by ihomp** [comment]
I've seen it added in Toast Wallet already, I've added it in Bithomp as well. I like the idea.
